---
name: Continuous Integration

on:
  push:
    branches:
    - 'master'
  pull_request:

jobs:
  continous-integration:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          pip install uv
      - name: Check formatting with ruff
        run: |
          uvx ruff format --diff
      - name: Lint with ruff
        run: |
          uvx ruff check
      - name: Run unit tests
        run: |
          uv run pytest
